"use client"

import type React from "react"

import { createContext, useContext, useEffect, useState } from "react"

export type Language = "en" | "ru" | "uz"

type TranslationRecord = Record<string, string>
type TranslationsType = Record<Language, TranslationRecord>

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  translations: TranslationsType
}

export const translations: TranslationsType = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.create": "Create Test",
    "nav.saved": "Saved Tests",
    "nav.analytics": "Analytics",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.logout": "Log out",
    "nav.customers": "Customers",
    "nav.invoices": "Invoices",
    "nav.reports": "Reports",

    // Common
    "common.search": "Search",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.loading": "Loading...",
    "common.upgrade": "Upgrade Plan",
    "common.save_changes": "Save Changes",
    "common.saving": "Saving...",
    "common.edit": "Edit",
    "common.duplicate": "Duplicate",
    "common.share": "Share",
    "common.delete": "Delete",
    "common.download": "Download",
    "common.actions": "Actions",
    "common.details": "Details",
    "common.export": "Export",
    "common.view_all": "View All",
    "common.filter": "Filter",
    "common.filter_by_subject": "Filter by subject",
    "common.all_subjects": "All Subjects",
    "common.grid_view": "Grid view",
    "common.list_view": "List view",
    "common.modified": "Modified",
    "common.questions": "questions",
    "common.from_last_month": "from last month",
    "common.name": "Name",
    "common.email": "Email",
    "common.status": "Status",
    "common.progress": "Progress",
    "common.score": "Score",
    "common.correct": "Correct",
    "common.time_spent": "Time Spent",
    "common.date": "Date",
    "common.active": "Active",
    "common.idle": "Idle",
    "common.left": "Left",
    "common.clean": "Clean",
    "common.suspicious": "Suspicious",
    "common.no_data": "No data available",
    "common.waiting": "Waiting",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your test activities and performance",
    "dashboard.welcome": "Welcome back! Here's an overview of your test activities.",
    "dashboard.create": "Create New Test",
    "dashboard.total_tests": "Total Tests",
    "dashboard.active_users": "Active Users",
    "dashboard.completion_rate": "Completion Rate",
    "dashboard.overview": "Overview",
    "dashboard.analytics": "Analytics",
    "dashboard.reports": "Reports",
    "dashboard.activity": "Test Generation Activity",
    "dashboard.activity_desc": "Number of tests generated over the past 30 days",
    "dashboard.recent": "Recent Activity",
    "dashboard.recent_desc": "Your latest test generation and editing activity",
    "dashboard.analytics_content": "Analytics Content",
    "dashboard.analytics_desc": "Detailed analytics will be displayed here",
    "dashboard.analytics_text":
      "This tab would contain more detailed analytics about test performance, user engagement, and other metrics.",
    "dashboard.reports_content": "Reports Content",
    "dashboard.reports_desc": "Generated reports will be displayed here",
    "dashboard.reports_text":
      "This tab would contain downloadable reports and summaries of test results and platform usage.",

    // Auth
    "auth.signin": "Sign In",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgot": "Forgot password?",
    "auth.no_account": "Don't have an account?",
    "auth.has_account": "Already have an account?",
    "auth.create_account": "Create Your Account",
    "auth.join": "Join TestGenius AI to create and manage tests",
    "auth.verify_email": "Verify Your Email",
    "auth.verify_code": "We've sent a 6-digit code to",
    "auth.enter_code": "Enter the 6-digit code sent to your email",
    "auth.resend_code": "Resend code",
    "auth.resend_in": "Resend code in",
    "auth.verify_continue": "Verify & Continue",
    "auth.back_to_signup": "Back to Sign Up",
    "auth.creating_account": "Creating Account...",
    "auth.verifying": "Verifying...",
    "auth.or_signup_with": "or sign up with",
    "auth.welcome_back": "Welcome back! Please enter your details.",
    "auth.signin_with": "or continue with",
    "auth.signing_in": "Signing in...",
    "auth.dev_mode": "Development Mode",
    "auth.backend_endpoint": "Backend API endpoint:",
    "auth.backend_running": "Make sure your backend server is running.",
    "auth.reset_password": "Reset Your Password",
    "auth.reset_instructions": "Enter your email to receive a password reset link",
    "auth.check_email": "Check Your Email",
    "auth.reset_link_sent": "We've sent a password reset link to",
    "auth.reset_email_info":
      "If an account exists with this email, you'll receive a password reset link shortly. Please check your inbox and spam folder.",
    "auth.send_different": "Send to a different email",
    "auth.back_to_signin": "Back to Sign In",
    "auth.sending": "Sending...",
    "auth.send_reset_link": "Send Reset Link",
    "auth.password_reset_complete": "Password Reset Complete",
    "auth.password_reset_success": "Your password has been successfully reset",
    "auth.create_new_password": "Create a new password for your account",
    "auth.new_password": "New Password",
    "auth.confirm_new_password": "Confirm New Password",
    "auth.resetting_password": "Resetting Password...",
    "auth.reset_password_button": "Reset Password",
    "auth.go_to_signin": "Go to Sign In",
    "auth.back_to_forgot": "Back to Forgot Password",
    "auth.invalid_token": "Invalid or missing reset token",
    "auth.last_name_optional": "Last Name (Optional)",
    "auth.confirm_password": "Confirm Password",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account settings and preferences.",
    "settings.general": "General",
    "settings.security": "Security",
    "settings.notifications": "Notifications",
    "settings.billing": "Billing",
    "settings.appearance": "Appearance",
    "settings.advanced": "Advanced",
    "settings.password": "Password",
    "settings.password.change": "Change your password or enable two-factor authentication.",
    "settings.appearance.title": "Appearance Settings",
    "settings.appearance.subtitle": "Customize the look and feel of your dashboard.",
    "settings.appearance.theme": "Theme Color",
    "settings.appearance.dark_mode": "Dark Mode",
    "settings.appearance.dark_mode.desc": "Toggle between light and dark mode.",
    "settings.appearance.font_size": "Font Size",
    "settings.appearance.reset": "Reset to Defaults",
    "settings.general_info": "General Information",
    "settings.general_desc": "Update your basic profile information.",
    "settings.full_name": "Full Name",
    "settings.email_address": "Email Address",
    "settings.organization": "Organization",
    "settings.role": "Role",
    "settings.bio": "Bio",
    "settings.bio_placeholder": "Tell us about yourself",
    "settings.language": "Language",
    "settings.timezone": "Timezone",

    // Language
    "language.english": "English",
    "language.russian": "Russian",
    "language.uzbek": "Uzbek",
    "language.select": "Select Language",

    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage your personal information and public profile.",
    "profile.personalInformations": "Personal Informations",
    "profile.name": "Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.address": "Address",
    "profile.city": "City",
    "profile.country": "Country",
    "profile.zip": "Zip",
    "profile.save": "Save",
    "profile.changePhoto": "Change Photo",
    "profile.location": "Location",
    "profile.occupation": "Occupation",
    "profile.bio": "Bio",
    "profile.bioPlaceholder": "Tell us about yourself",
    "profile.bioDefault":
      "I'm a high school teacher specializing in mathematics and computer science. I've been using TestGenius AI to create engaging assessments for my students.",
    "profile.socialProfiles": "Social Profiles",
    "profile.website": "Website",
    "profile.github": "GitHub",
    "profile.twitter": "Twitter",
    "profile.linkedin": "LinkedIn",
    "profile.overview": "Overview",
    "profile.overviewDescription": "Your profile overview and recent activities.",
    "profile.activityStats": "Activity Stats",
    "profile.activityStatsDescription": "Your recent activity statistics.",
    "profile.testsCreated": "Tests Created",
    "profile.activeStudents": "Active Students",
    "profile.completionRate": "Completion Rate",
    "profile.averageScore": "Average Score",
    "profile.recentActivity": "Recent Activity",
    "profile.recentActivityDescription": "Your recent activity logs.",
    "profile.tests": "Tests",
    "profile.students": "Students",
    "profile.results": "Results",
    "profile.testsName": "Test Name",
    "profile.testsSubject": "Subject",
    "profile.testsQuestions": "Questions",
    "profile.viewAllTests": "View All Tests",
    "profile.studentsName": "Name",
    "profile.studentsEmail": "Email",
    "profile.studentsTests": "Tests",
    "profile.studentsScore": "Score",
    "profile.viewAllStudents": "View All Students",
    "profile.resultsTestName": "Test Name",
    "profile.resultsStudent": "Student",
    "profile.resultsScore": "Score",
    "profile.resultsTimeSpent": "Time Spent",
    "profile.resultsDate": "Date",
    "profile.viewAllResults": "View All Results",

    // Theme
    "theme.red": "Red",
    "theme.orange": "Orange",
    "theme.yellow": "Yellow",
    "theme.green": "Green",
    "theme.blue": "Blue",
    "theme.purple": "Purple",
    "theme.default": "Default",

    // Test Preview
    "test_preview.title": "Test Preview",
    "test_preview.question": "Question",
    "test_preview.correct_answer": "Correct Answer",
    "test_preview.start_test": "Start Test",
    "test_preview.true": "True",
    "test_preview.false": "False",
    "test_preview.matches": "Matches",
    "test_preview.options": "Options",
    "test_preview.no_questions": "No questions available",

    // Monitor
    "monitor.title": "Test Monitoring",
    "monitor.subtitle": "Monitor test progress and participant activity",
    "monitor.starting": "Starting...",
    "monitor.start": "Start Test",
    "monitor.resume": "Resume Test",
    "monitor.pause": "Pause Test",
    "monitor.preview": "Preview Test",
    "monitor.attention": "Attention",
    "monitor.time_remaining": "Time Remaining",
    "monitor.participants": "Participants",
    "monitor.average_progress": "Average Progress",
    "monitor.participants_tab": "Participants",
    "monitor.results_tab": "Results",
    "monitor.participants_list": "Participants List",
    "monitor.participant_actions": "Actions",
    "monitor.view_details": "View Details",
    "monitor.send_message": "Send Message",
    "monitor.remove_participant": "Remove Participant",
    "monitor.avg_score": "Average Score",
    "monitor.completion_rate": "Completion Rate",
    "monitor.avg_time": "Average Time",
    "monitor.detailed_results": "Detailed Results",
    "monitor.detailed_results_desc": "Comprehensive breakdown of individual performance",
    "monitor.generate_report": "Generate Report",
    "monitor.export_results": "Export Results",
    "monitor.access_code": "Access Code",
    "monitor.qr_code": "QR Code",
    "monitor.waiting_participants": "Waiting for participants",
    "monitor.participants_appear": "Participants will appear here once they join the test",
    "monitor.no_results": "No results available",
    "monitor.results_available": "Results will be available once participants complete the test",

    // Saved Tests
    "saved.title": "Saved Tests",
    "saved.subtitle": "View and manage your saved tests",

    // Create Test
    "create.title": "Create Test",
    "create.subtitle": "Generate a new test using AI",
    "create.connected": "Connected to server",
    "create.not_connected": "Not connected to server",
    "create.choose_method": "Choose method",
    "create.configure_test": "Configure test",
    "create.preview_test": "Preview test",
    "create.form_method": "Create from Form",
    "create.form_desc": "Enter subject, topics, and other details to generate a test",
    "create.book_method": "Create from Book",
    "create.book_desc": "Upload a book (PDF, DOCX, TXT) and select topics to generate a test",
    "create.drag_drop": "Drag and drop your file here",
    "create.file_types": "Supports PDF, DOCX, and TXT files",
    "create.browse_files": "Browse files",
    "create.remove": "Remove",
    "create.process_book": "Process Book",
    "create.processing": "Processing book...",
    "create.extracted_topics": "Extracted Topics",
    "create.select_topics": "Select the topics you want to include in your test",
    "create.subject": "Subject",
    "create.subject_placeholder": "e.g., Mathematics, Physics, History",
    "create.topic": "Topic",
    "create.topic_placeholder": "e.g., Algebra, Calculus, Geometry",
    "create.difficulty": "Difficulty",
    "create.easy": "Easy",
    "create.medium": "Medium",
    "create.hard": "Hard",
    "create.format": "Format",
    "create.multiple_choice": "Multiple Choice",
    "create.true_false": "True/False",
    "create.short_answer": "Short Answer",
    "create.language": "Language",
    "create.number_of_questions": "Number of Questions",
    "create.additional_instructions": "Additional Instructions (Optional)",
    "create.instructions_placeholder": "Any specific instructions or requirements for the test",
    "create.generating": "Generating...",
    "create.generate_ai": "Generate with AI",
    "create.generating_test": "Generating test...",
    "create.skip_loading": "Skip Loading",
    "create.save_test": "Save Test",
    "create.test_saved": "Test saved successfully!",

    // Analytics
    "analytics.title": "Analytics Dashboard",
    "analytics.subtitle": "Comprehensive insights into your test performance and user engagement.",
    "analytics.overview": "Overview",
    "analytics.performance": "Performance",
    "analytics.subjects": "Subjects",
    "analytics.timeframe": "Timeframe",
    "analytics.filter": "Filter",
    "analytics.download": "Download Report",
    "analytics.tests_created": "Tests Created",
    "analytics.participants": "Participants",
    "analytics.completion_rate": "Completion Rate",
    "analytics.avg_score": "Average Score",
    "analytics.from_last_month": "from last month",
    "analytics.test_activity": "Test Activity",
    "analytics.test_activity_desc": "Number of tests created and participants over time",
    "analytics.performance_dist": "Performance Distribution",
    "analytics.performance_dist_desc": "Distribution of test scores across all participants",
    "analytics.subject_dist": "Subject Distribution",
    "analytics.subject_dist_desc": "Breakdown of tests by subject area",
    "analytics.recent_tests": "Recent Tests",
    "analytics.view_all": "View All",
    "analytics.test_name": "Test Name",
    "analytics.subject": "Subject",
    "analytics.participants_count": "Participants",
    "analytics.avg_score_label": "Avg. Score",
    "analytics.date": "Date",
    "analytics.chart_type": "Chart Type",
    "analytics.bar": "Bar",
    "analytics.line": "Line",
    "analytics.area": "Area",
    "analytics.showing_data": "Showing data for",
    "analytics.months": "months",
    "analytics.performance_chart": "Performance Distribution Chart",
    "analytics.subject_chart": "Subject Distribution Chart",

    // Pricing
    "pricing.title": "Pricing Plans",
    "pricing.subtitle": "Choose the plan that best fits your needs",
    "pricing.popular": "Popular",
    "pricing.per_month": "/month",
    "pricing.select_plan": "Select Plan",
    "pricing.basic": "Basic",
    "pricing.basic_desc": "Essential features for small tests",
    "pricing.standard": "Standard",
    "pricing.standard_desc": "Advanced features for professional use",
    "pricing.premium": "Premium",
    "pricing.premium_desc": "Enterprise-grade testing solution",
    "pricing.plan_selected": "Plan Selected",
    "pricing.test_ready": "Your test is ready to share",
    "pricing.unique_code": "Unique Access Code",
    "pricing.share_code": "Share this code with participants to join the test",
    "pricing.scan_qr": "Scan this QR code to join the test",
    "pricing.invite_link": "Invite Link",
    "pricing.share_link": "Share this link with participants to join the test",
    "pricing.back_to_plans": "Back to Plans",
    "pricing.go_to_monitoring": "Go to Monitoring",
  },
  ru: {
    // Navigation
    "nav.dashboard": "Панель управления",
    "nav.create": "Создать тест",
    "nav.saved": "Сохраненные тесты",
    "nav.analytics": "Аналитика",
    "nav.settings": "Настройки",
    "nav.profile": "Профиль",
    "nav.logout": "Выйти",
    "nav.customers": "Клиенты",
    "nav.invoices": "Счета",
    "nav.reports": "Отчеты",

    // Common
    "common.search": "Поиск",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.submit": "Отправить",
    "common.loading": "Загрузка...",
    "common.upgrade": "Улучшить план",
    "common.save_changes": "Сохранить изменения",
    "common.saving": "Сохранение...",
    "common.edit": "Редактировать",
    "common.duplicate": "Дублировать",
    "common.share": "Поделиться",
    "common.delete": "Удалить",
    "common.download": "Скачать",
    "common.actions": "Действия",
    "common.details": "Подробности",
    "common.export": "Экспорт",
    "common.view_all": "Посмотреть все",
    "common.filter": "Фильтр",
    "common.filter_by_subject": "Фильтровать по предмету",
    "common.all_subjects": "Все предметы",
    "common.grid_view": "Вид сеткой",
    "common.list_view": "Вид списком",
    "common.modified": "Изменено",
    "common.questions": "вопросов",
    "common.from_last_month": "с прошлого месяца",
    "common.name": "Имя",
    "common.email": "Электронная почта",
    "common.status": "Статус",
    "common.progress": "Прогресс",
    "common.score": "Оценка",
    "common.correct": "Правильно",
    "common.time_spent": "Затраченное время",
    "common.date": "Дата",
    "common.active": "Активен",
    "common.idle": "Неактивен",
    "common.left": "Покинул",
    "common.clean": "Чисто",
    "common.suspicious": "Подозрительно",
    "common.no_data": "Нет доступных данных",
    "common.waiting": "Ожидание",

    // Dashboard
    "dashboard.title": "Панель управления",
    "dashboard.subtitle": "Обзор ваших тестовых активностей и производительности",
    "dashboard.welcome": "С возвращением! Вот обзор ваших тестовых активностей.",
    "dashboard.create": "Создать новый тест",
    "dashboard.total_tests": "Всего тестов",
    "dashboard.active_users": "Активные пользователи",
    "dashboard.completion_rate": "Процент завершения",
    "dashboard.overview": "Обзор",
    "dashboard.analytics": "Аналитика",
    "dashboard.reports": "Отчеты",
    "dashboard.activity": "Активность создания тестов",
    "dashboard.activity_desc": "Количество тестов, созданных за последние 30 дней",
    "dashboard.recent": "Недавняя активность",
    "dashboard.recent_desc": "Ваша последняя активность по созданию и редактированию тестов",
    "dashboard.analytics_content": "Содержание аналитики",
    "dashboard.analytics_desc": "Здесь будет отображаться подробная аналитика",
    "dashboard.analytics_text":
      "Эта вкладка будет содержать более подробную аналитику о производительности тестов, вовлеченности пользователей и других показателях.",
    "dashboard.reports_content": "Содержание отчетов",
    "dashboard.reports_desc": "Здесь будут отображаться сгенерированные отчеты",
    "dashboard.reports_text":
      "Эта вкладка будет содержать загружаемые отчеты и сводки результатов тестов и использования платформы.",

    // Auth
    "auth.signin": "Вход",
    "auth.signup": "Регистрация",
    "auth.email": "Электронная почта",
    "auth.password": "Пароль",
    "auth.forgot": "Забыли пароль?",
    "auth.no_account": "Нет аккаунта?",
    "auth.has_account": "Уже есть аккаунт?",
    "auth.create_account": "Создайте свой аккаунт",
    "auth.join": "Присоединяйтесь к TestGenius AI для создания и управления тестами",
    "auth.verify_email": "Подтвердите вашу электронную почту",
    "auth.verify_code": "Мы отправили 6-значный код на",
    "auth.enter_code": "Введите 6-значный код, отправленный на вашу электронную почту",
    "auth.resend_code": "Отправить код повторно",
    "auth.resend_in": "Повторная отправка через",
    "auth.verify_continue": "Подтвердить и продолжить",
    "auth.back_to_signup": "Вернуться к регистрации",
    "auth.creating_account": "Создание аккаунта...",
    "auth.verifying": "Проверка...",
    "auth.or_signup_with": "или зарегистрируйтесь через",
    "auth.welcome_back": "Добро пожаловать! Пожалуйста, введите ваши данные.",
    "auth.signin_with": "или продолжить с",
    "auth.signing_in": "Вход в систему...",
    "auth.dev_mode": "Режим разработки",
    "auth.backend_endpoint": "Конечная точка бэкенда:",
    "auth.backend_running": "Убедитесь, что ваш сервер бэкенда запущен.",
    "auth.reset_password": "Сбросить пароль",
    "auth.reset_instructions": "Введите вашу электронную почту, чтобы получить ссылку для сброса пароля",
    "auth.check_email": "Проверьте вашу электронную почту",
    "auth.reset_link_sent": "Мы отправили ссылку для сброса пароля на",
    "auth.reset_email_info":
      "Если аккаунт с этой электронной почтой существует, вы вскоре получите ссылку для сброса пароля. Пожалуйста, проверьте вашу папку входящих сообщений и спам.",
    "auth.send_different": "Отправить на другую электронную почту",
    "auth.back_to_signin": "Вернуться к входу",
    "auth.sending": "Отправка...",
    "auth.send_reset_link": "Отправить ссылку для сброса",
    "auth.password_reset_complete": "Сброс пароля завершен",
    "auth.password_reset_success": "Ваш пароль был успешно сброшен",
    "auth.create_new_password": "Создайте новый пароль для вашего аккаунта",
    "auth.new_password": "Новый пароль",
    "auth.confirm_new_password": "Подтвердите новый пароль",
    "auth.resetting_password": "Сброс пароля...",
    "auth.reset_password_button": "Сбросить пароль",
    "auth.go_to_signin": "Перейти к входу",
    "auth.back_to_forgot": "Вернуться к восстановлению пароля",
    "auth.invalid_token": "Недействительный или отсутствующий токен сброса",
    "auth.last_name_optional": "Фамилия (необязательно)",
    "auth.confirm_password": "Подтвердите пароль",

    // Settings
    "settings.title": "Настройки",
    "settings.subtitle": "Управляйте настройками вашего аккаунта и предпочтениями.",
    "settings.general": "Общие",
    "settings.security": "Безопасность",
    "settings.notifications": "Уведомления",
    "settings.billing": "Оплата",
    "settings.appearance": "Внешний вид",
    "settings.advanced": "Расширенные",
    "settings.password": "Пароль",
    "settings.password.change": "Измените пароль или включите двухфакторную аутентификацию.",
    "settings.appearance.title": "Настройки внешнего вида",
    "settings.appearance.subtitle": "Настройте внешний вид вашей панели управления.",
    "settings.appearance.theme": "Цветовая тема",
    "settings.appearance.dark_mode": "Темный режим",
    "settings.appearance.dark_mode.desc": "Переключение между светлым и темным режимом.",
    "settings.appearance.font_size": "Размер шрифта",
    "settings.appearance.reset": "Сбросить настройки",
    "settings.general_info": "Общая информация",
    "settings.general_desc": "Обновите вашу основную информацию профиля.",
    "settings.full_name": "Полное имя",
    "settings.email_address": "Адрес электронной почты",
    "settings.organization": "Организация",
    "settings.role": "Роль",
    "settings.bio": "Биография",
    "settings.bio_placeholder": "Расскажите о себе",
    "settings.language": "Язык",
    "settings.timezone": "Часовой пояс",

    // Language
    "language.english": "Английский",
    "language.russian": "Русский",
    "language.uzbek": "Узбекский",
    "language.select": "Выбрать язык",

    // Profile
    "profile.title": "Профиль",
    "profile.subtitle": "Управляйте вашей личной информацией и публичным профилем.",
    "profile.personalInformations": "Личная информация",
    "profile.name": "Имя",
    "profile.lastName": "Фамилия",
    "profile.email": "Электронная почта",
    "profile.phone": "Телефон",
    "profile.address": "Адрес",
    "profile.city": "Город",
    "profile.country": "Страна",
    "profile.zip": "Индекс",
    "profile.save": "Сохранить",
    "profile.changePhoto": "Изменить фото",
    "profile.location": "Местоположение",
    "profile.occupation": "Занятие",
    "profile.bio": "Биография",
    "profile.bioPlaceholder": "Расскажите о себе",
    "profile.bioDefault":
      "Я учитель средней школы, специализирующийся на математике и информатике. Я использую TestGenius AI для создания увлекательных оценок для моих учеников.",
    "profile.socialProfiles": "Социальные профили",
    "profile.website": "Веб-сайт",
    "profile.github": "GitHub",
    "profile.twitter": "Twitter",
    "profile.linkedin": "LinkedIn",
    "profile.overview": "Обзор",
    "profile.overviewDescription": "Обзор вашего профиля и недавние действия.",
    "profile.activityStats": "Статистика активности",
    "profile.activityStatsDescription": "Статистика вашей недавней активности.",
    "profile.testsCreated": "Создано тестов",
    "profile.activeStudents": "Активные студенты",
    "profile.completionRate": "Процент завершения",
    "profile.averageScore": "Средний балл",
    "profile.recentActivity": "Недавняя активность",
    "profile.recentActivityDescription": "Ваши журналы недавней активности.",
    "profile.tests": "Тесты",
    "profile.students": "Студенты",
    "profile.results": "Результаты",
    "profile.testsName": "Название теста",
    "profile.testsSubject": "Предмет",
    "profile.testsQuestions": "Вопросы",
    "profile.viewAllTests": "Посмотреть все тесты",
    "profile.studentsName": "Имя",
    "profile.studentsEmail": "Электронная почта",
    "profile.studentsTests": "Тесты",
    "profile.studentsScore": "Балл",
    "profile.viewAllStudents": "Посмотреть всех студентов",
    "profile.resultsTestName": "Название теста",
    "profile.resultsStudent": "Студент",
    "profile.resultsScore": "Балл",
    "profile.resultsTimeSpent": "Затраченное время",
    "profile.resultsDate": "Дата",
    "profile.viewAllResults": "Посмотреть все результаты",

    // Theme
    "theme.red": "Красный",
    "theme.orange": "Оранжевый",
    "theme.yellow": "Жёлтый",
    "theme.green": "Зелёный",
    "theme.blue": "Синий",
    "theme.purple": "Фиолетовый",
    "theme.default": "Стандартный",

    // Test Preview
    "test_preview.title": "Предварительный просмотр теста",
    "test_preview.question": "Вопрос",
    "test_preview.correct_answer": "Правильный ответ",
    "test_preview.start_test": "Начать тест",
    "test_preview.true": "Верно",
    "test_preview.false": "Неверно",
    "test_preview.matches": "Соответствия",
    "test_preview.options": "Варианты",
    "test_preview.no_questions": "Нет доступных вопросов",

    // Monitor
    "monitor.title": "Мониторинг теста",
    "monitor.subtitle": "Отслеживание прогресса теста и активности участников",
    "monitor.starting": "Запуск...",
    "monitor.start": "Начать тест",
    "monitor.resume": "Возобновить тест",
    "monitor.pause": "Приостановить тест",
    "monitor.preview": "Предварительный просмотр",
    "monitor.attention": "Внимание",
    "monitor.time_remaining": "Оставшееся время",
    "monitor.participants": "Участники",
    "monitor.average_progress": "Средний прогресс",
    "monitor.participants_tab": "Участники",
    "monitor.results_tab": "Результаты",
    "monitor.participants_list": "Список участников",
    "monitor.participant_actions": "Действия",
    "monitor.view_details": "Просмотр деталей",
    "monitor.send_message": "Отправить сообщение",
    "monitor.remove_participant": "Удалить участника",
    "monitor.avg_score": "Средний балл",
    "monitor.completion_rate": "Процент завершения",
    "monitor.avg_time": "Среднее время",
    "monitor.detailed_results": "Подробные результаты",
    "monitor.detailed_results_desc": "Комплексный анализ индивидуальной производительности",
    "monitor.generate_report": "Создать отчет",
    "monitor.export_results": "Экспорт результатов",
    "monitor.access_code": "Код доступа",
    "monitor.qr_code": "QR-код",
    "monitor.waiting_participants": "Ожидание участников",
    "monitor.participants_appear": "Участники появятся здесь, когда присоединятся к тесту",
    "monitor.no_results": "Нет доступных результатов",
    "monitor.results_available": "Результаты будут доступны после завершения теста участниками",

    // Saved Tests
    "saved.title": "Сохраненные тесты",
    "saved.subtitle": "Просмотр и управление сохраненными тестами",

    // Create Test
    "create.title": "Создать тест",
    "create.subtitle": "Создание нового теста с помощью ИИ",
    "create.connected": "Подключено к серверу",
    "create.not_connected": "Не подключено к серверу",
    "create.choose_method": "Выберите метод",
    "create.configure_test": "Настройка теста",
    "create.preview_test": "Предварительный просмотр теста",
    "create.form_method": "Создать из формы",
    "create.form_desc": "Введите предмет, темы и другие детали для создания теста",
    "create.book_method": "Создать из книги",
    "create.book_desc": "Загрузите книгу (PDF, DOCX, TXT) и выберите темы для создания теста",
    "create.drag_drop": "Перетащите файл сюда",
    "create.file_types": "Поддерживаются форматы PDF, DOCX и TXT",
    "create.browse_files": "Обзор файлов",
    "create.remove": "Удалить",
    "create.process_book": "Обработать книгу",
    "create.processing": "Обработка книги...",
    "create.extracted_topics": "Извлеченные темы",
    "create.select_topics": "Выберите темы, которые вы хотите включить в тест",
    "create.subject": "Предмет",
    "create.subject_placeholder": "например, Математика, Физика, История",
    "create.topic": "Тема",
    "create.topic_placeholder": "например, Алгебра, Исчисление, Геометрия",
    "create.difficulty": "Сложность",
    "create.easy": "Легкий",
    "create.medium": "Средний",
    "create.hard": "Сложный",
    "create.format": "Формат",
    "create.multiple_choice": "Множественный выбор",
    "create.true_false": "Верно/Неверно",
    "create.short_answer": "Короткий ответ",
    "create.language": "Язык",
    "create.number_of_questions": "Количество вопросов",
    "create.additional_instructions": "Дополнительные инструкции (необязательно)",
    "create.instructions_placeholder": "Любые конкретные инструкции или требования для теста",
    "create.generating": "Генерация...",
    "create.generate_ai": "Сгенерировать с помощью ИИ",
    "create.generating_test": "Генерация теста...",
    "create.skip_loading": "Пропустить загрузку",
    "create.save_test": "Сохранить тест",
    "create.test_saved": "Тест успешно сохранен!",

    // Analytics
    "analytics.title": "Панель аналитики",
    "analytics.subtitle": "Комплексный анализ эффективности тестов и вовлеченности пользователей.",
    "analytics.overview": "Обзор",
    "analytics.performance": "Производительность",
    "analytics.subjects": "Предметы",
    "analytics.timeframe": "Временной период",
    "analytics.filter": "Фильтр",
    "analytics.download": "Скачать отчет",
    "analytics.tests_created": "Созданные тесты",
    "analytics.participants": "Участники",
    "analytics.completion_rate": "Процент завершения",
    "analytics.avg_score": "Средний балл",
    "analytics.from_last_month": "с прошлого месяца",
    "analytics.test_activity": "Активность тестирования",
    "analytics.test_activity_desc": "Количество созданных тестов и участников с течением времени",
    "analytics.performance_dist": "Распределение производительности",
    "analytics.performance_dist_desc": "Распределение результатов тестов среди всех участников",
    "analytics.subject_dist": "Распределение по предметам",
    "analytics.subject_dist_desc": "Разбивка тестов по предметным областям",
    "analytics.recent_tests": "Недавние тесты",
    "analytics.view_all": "Посмотреть все",
    "analytics.test_name": "Название теста",
    "analytics.subject": "Предмет",
    "analytics.participants_count": "Участники",
    "analytics.avg_score_label": "Ср. балл",
    "analytics.date": "Дата",
    "analytics.chart_type": "Тип диаграммы",
    "analytics.bar": "Столбчатая",
    "analytics.line": "Линейная",
    "analytics.area": "Область",
    "analytics.showing_data": "Показаны данные за",
    "analytics.months": "месяцев",
    "analytics.performance_chart": "Диаграмма распределения производительности",
    "analytics.subject_chart": "Диаграмма распределения по предметам",

    // Pricing
    "pricing.title": "Тарифные планы",
    "pricing.subtitle": "Выберите план, который лучше всего соответствует вашим потребностям",
    "pricing.popular": "Популярный",
    "pricing.per_month": "/месяц",
    "pricing.select_plan": "Выбрать план",
    "pricing.basic": "Базовый",
    "pricing.basic_desc": "Основные функции для небольших тестов",
    "pricing.standard": "Стандартный",
    "pricing.standard_desc": "Расширенные функции для профессионального использования",
    "pricing.premium": "Премиум",
    "pricing.premium_desc": "Решение корпоративного уровня для тестирования",
    "pricing.plan_selected": "План выбран",
    "pricing.test_ready": "Ваш тест готов к распространению",
    "pricing.unique_code": "Уникальный код доступа",
    "pricing.share_code": "Поделитесь этим кодом с участниками для присоединения к тесту",
    "pricing.scan_qr": "Отсканируйте этот QR-код для присоединения к тесту",
    "pricing.invite_link": "Ссылка для приглашения",
    "pricing.share_link": "Поделитесь этой ссылкой с участниками для присоединения к тесту",
    "pricing.back_to_plans": "Вернуться к планам",
    "pricing.go_to_monitoring": "Перейти к мониторингу",
  },
  uz: {
    // Navigation
    "nav.dashboard": "Boshqaruv paneli",
    "nav.create": "Test yaratish",
    "nav.saved": "Saqlangan testlar",
    "nav.analytics": "Tahlillar",
    "nav.settings": "Sozlamalar",
    "nav.profile": "Profil",
    "nav.logout": "Chiqish",
    "nav.customers": "Mijozlar",
    "nav.invoices": "Hisob-fakturalar",
    "nav.reports": "Hisobotlar",

    // Common
    "common.search": "Qidirish",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.back": "Orqaga",
    "common.next": "Keyingi",
    "common.submit": "Yuborish",
    "common.loading": "Yuklanmoqda...",
    "common.upgrade": "Tarifni yangilash",
    "common.save_changes": "O'zgarishlarni saqlash",
    "common.saving": "Saqlanmoqda...",
    "common.edit": "Tahrirlash",
    "common.duplicate": "Nusxalash",
    "common.share": "Ulashish",
    "common.delete": "O'chirish",
    "common.download": "Yuklab olish",
    "common.actions": "Harakatlar",
    "common.details": "Tafsilotlar",
    "common.export": "Eksport",
    "common.view_all": "Barchasini ko'rish",
    "common.filter": "Filtr",
    "common.filter_by_subject": "Fan bo'yicha filtrlash",
    "common.all_subjects": "Barcha fanlar",
    "common.grid_view": "Katakchalar ko'rinishi",
    "common.list_view": "Ro'yxat ko'rinishi",
    "common.modified": "O'zgartirilgan",
    "common.questions": "savollar",
    "common.from_last_month": "o'tgan oydan",
    "common.name": "Ism",
    "common.email": "Elektron pochta",
    "common.status": "Holat",
    "common.progress": "Progress",
    "common.score": "Ball",
    "common.correct": "To'g'ri",
    "common.time_spent": "Sarflangan vaqt",
    "common.date": "Sana",
    "common.active": "Faol",
    "common.idle": "Nofaol",
    "common.left": "Chiqib ketdi",
    "common.clean": "Toza",
    "common.suspicious": "Shubhali",
    "common.no_data": "Ma'lumot mavjud emas",
    "common.waiting": "Kutilmoqda",

    // Dashboard
    "dashboard.title": "Boshqaruv paneli",
    "dashboard.subtitle": "Test faoliyatingiz va samaradorligingiz haqida umumiy ma'lumot",
    "dashboard.welcome": "Qaytib kelganingiz bilan! Bu yerda test faoliyatingiz haqida umumiy ma'lumot.",
    "dashboard.create": "Yangi test yaratish",
    "dashboard.total_tests": "Jami testlar",
    "dashboard.active_users": "Faol foydalanuvchilar",
    "dashboard.completion_rate": "Tugatish darajasi",
    "dashboard.overview": "Umumiy ko'rinish",
    "dashboard.analytics": "Tahlillar",
    "dashboard.reports": "Hisobotlar",
    "dashboard.activity": "Test yaratish faoliyati",
    "dashboard.activity_desc": "So'nggi 30 kun ichida yaratilgan testlar soni",
    "dashboard.recent": "So'nggi faoliyat",
    "dashboard.recent_desc": "Sizning so'nggi test yaratish va tahrirlash faoliyatingiz",
    "dashboard.analytics_content": "Tahlillar mazmuni",
    "dashboard.analytics_desc": "Batafsil tahlillar shu yerda ko'rsatiladi",
    "dashboard.analytics_text":
      "Bu yorliq test samaradorligi, foydalanuvchilar faolligi va boshqa ko'rsatkichlar haqida batafsil tahlillarni o'z ichiga oladi.",
    "dashboard.reports_content": "Hisobotlar mazmuni",
    "dashboard.reports_desc": "Yaratilgan hisobotlar shu yerda ko'rsatiladi",
    "dashboard.reports_text":
      "Bu yorliq yuklab olinadigan hisobotlar va test natijalari hamda platforma foydalanishi bo'yicha xulosalarni o'z ichiga oladi.",

    // Auth
    "auth.signin": "Kirish",
    "auth.signup": "Ro'yxatdan o'tish",
    "auth.email": "Elektron pochta",
    "auth.password": "Parol",
    "auth.forgot": "Parolni unutdingizmi?",
    "auth.no_account": "Hisobingiz yo'qmi?",
    "auth.has_account": "Hisobingiz bormi?",
    "auth.create_account": "Hisobingizni yarating",
    "auth.join": "Testlarni yaratish va boshqarish uchun TestGenius AI ga qo'shiling",
    "auth.verify_email": "Elektron pochtangizni tasdiqlang",
    "auth.verify_code": "Biz 6 raqamli kodni yubordik",
    "auth.enter_code": "Elektron pochtangizga yuborilgan 6 raqamli kodni kiriting",
    "auth.resend_code": "Kodni qayta yuborish",
    "auth.resend_in": "Kodni qayta yuborish vaqti",
    "auth.verify_continue": "Tasdiqlash va davom etish",
    "auth.back_to_signup": "Ro'yxatdan o'tishga qaytish",
    "auth.creating_account": "Hisob yaratilmoqda...",
    "auth.verifying": "Tasdiqlanmoqda...",
    "auth.or_signup_with": "yoki bular orqali ro'yxatdan o'ting",
    "auth.welcome_back": "Qaytib kelganingiz bilan! Iltimos, ma'lumotlaringizni kiriting.",
    "auth.signin_with": "yoki bular orqali davom eting",
    "auth.signing_in": "Kirilmoqda...",
    "auth.dev_mode": "Ishlab chiqish rejimi",
    "auth.backend_endpoint": "Backend endpointi:",
    "auth.backend_running": "Backend serveringiz ishlab turganiga ishonch hosil qiling.",
    "auth.reset_password": "Parolni tiklash",
    "auth.reset_instructions": "Parolni tiklash havolasini olish uchun elektron pochtangizni kiriting",
    "auth.check_email": "Elektron pochtangizni tekshiring",
    "auth.reset_link_sent": "Biz parolni tiklash havolasini yubordik",
    "auth.reset_email_info":
      "Agar bu elektron pochta bilan hisob mavjud bo'lsa, tez orada parolni tiklash havolasini olasiz. Iltimos, kiruvchi xabarlar va spam papkangizni tekshiring.",
    "auth.send_different": "Boshqa elektron pochtaga yuborish",
    "auth.back_to_signin": "Kirishga qaytish",
    "auth.sending": "Yuborilmoqda...",
    "auth.send_reset_link": "Tiklash havolasini yuborish",
    "auth.password_reset_complete": "Parol tiklash yakunlandi",
    "auth.password_reset_success": "Parolingiz muvaffaqiyatli tiklandi",
    "auth.create_new_password": "Hisobingiz uchun yangi parol yarating",
    "auth.new_password": "Yangi parol",
    "auth.confirm_new_password": "Yangi parolni tasdiqlang",
    "auth.resetting_password": "Parol tiklanmoqda...",
    "auth.reset_password_button": "Parolni tiklash",
    "auth.go_to_signin": "Kirishga o'tish",
    "auth.back_to_forgot": "Parolni unutdimga qaytish",
    "auth.invalid_token": "Yaroqsiz yoki yo'q tiklash tokeni",
    "auth.last_name_optional": "Familiya (ixtiyoriy)",
    "auth.confirm_password": "Parolni tasdiqlang",

    // Settings
    "settings.title": "Sozlamalar",
    "settings.subtitle": "Hisobingiz sozlamalari va afzalliklarini boshqaring.",
    "settings.general": "Umumiy",
    "settings.security": "Xavfsizlik",
    "settings.notifications": "Bildirishnomalar",
    "settings.billing": "To'lov",
    "settings.appearance": "Ko'rinish",
    "settings.advanced": "Kengaytirilgan",
    "settings.password": "Parol",
    "settings.password.change": "Parolingizni o'zgartiring yoki ikki faktorli autentifikatsiyani yoqing.",
    "settings.appearance.title": "Ko'rinish sozlamalari",
    "settings.appearance.subtitle": "Boshqaruv panelingizning ko'rinishini sozlang.",
    "settings.appearance.theme": "Rang mavzusi",
    "settings.appearance.dark_mode": "Qorong'i rejim",
    "settings.appearance.dark_mode.desc": "Yorug' va qorong'i rejim o'rtasida almashtirish.",
    "settings.appearance.font_size": "Shrift o'lchami",
    "settings.appearance.reset": "Standart sozlamalarga qaytarish",
    "settings.general_info": "Umumiy ma'lumot",
    "settings.general_desc": "Asosiy profil ma'lumotlaringizni yangilang.",
    "settings.full_name": "To'liq ism",
    "settings.email_address": "Elektron pochta manzili",
    "settings.organization": "Tashkilot",
    "settings.role": "Lavozim",
    "settings.bio": "Tarjimai hol",
    "settings.bio_placeholder": "O'zingiz haqida gapirib bering",
    "settings.language": "Til",
    "settings.timezone": "Vaqt mintaqasi",

    // Language
    "language.english": "Ingliz",
    "language.russian": "Rus",
    "language.uzbek": "O'zbek",
    "language.select": "Tilni tanlang",

    // Profile
    "profile.title": "Profil",
    "profile.subtitle": "Shaxsiy ma'lumotlaringiz va ommaviy profilingizni boshqaring.",
    "profile.personalInformations": "Shaxsiy ma'lumotlaringiz",
    "profile.name": "Ismingiz",
    "profile.lastName": "Familiyangiz",
    "profile.email": "Elektron pochta",
    "profile.phone": "Telefon raqamingiz",
    "profile.address": "Manzilingiz",
    "profile.city": "Shahri",
    "profile.country": "Mamlakat",
    "profile.zip": "Zip kod",
    "profile.save": "Saqlash",
    "profile.changePhoto": "Suratni o'zgartirish",
    "profile.location": "Manzil",
    "profile.occupation": "Kasb",
    "profile.bio": "Tarjimai hol",
    "profile.bioPlaceholder": "O'zingiz haqida gapirib bering",
    "profile.bioDefault":
      "Men matematika va informatika fanlari bo'yicha ixtisoslashgan o'rta maktab o'qituvchisiman. Men o'quvchilarim uchun qiziqarli baholashlar yaratish uchun TestGenius AI dan foydalanaman.",
    "profile.socialProfiles": "Ijtimoiy profillar",
    "profile.website": "Veb-sayt",
    "profile.github": "GitHub",
    "profile.twitter": "Twitter",
    "profile.linkedin": "LinkedIn",
    "profile.overview": "Umumiy ko'rinish",
    "profile.overviewDescription": "Profilingiz umumiy ko'rinishi va so'nggi faoliyatlar.",
    "profile.activityStats": "Faoliyat statistikasi",
    "profile.activityStatsDescription": "Sizning so'nggi faoliyatingiz statistikasi.",
    "profile.testsCreated": "Yaratilgan testlar",
    "profile.activeStudents": "Faol talabalar",
    "profile.completionRate": "Tugatish darajasi",
    "profile.averageScore": "O'rtacha ball",
    "profile.recentActivity": "So'nggi faoliyat",
    "profile.recentActivityDescription": "Sizning so'nggi faoliyat jurnallaringiz.",
    "profile.tests": "Testlar",
    "profile.students": "Talabalar",
    "profile.results": "Natijalar",
    "profile.testsName": "Test nomi",
    "profile.testsSubject": "Fan",
    "profile.testsQuestions": "Savollar",
    "profile.viewAllTests": "Barcha testlarni ko'rish",
    "profile.studentsName": "Ism",
    "profile.studentsEmail": "Elektron pochta",
    "profile.studentsTests": "Testlar",
    "profile.studentsScore": "Ball",
    "profile.viewAllStudents": "Barcha talabalarni ko'rish",
    "profile.resultsTestName": "Test nomi",
    "profile.resultsStudent": "Talaba",
    "profile.resultsScore": "Ball",
    "profile.resultsTimeSpent": "Sarflangan vaqt",
    "profile.resultsDate": "Sana",
    "profile.viewAllResults": "Barcha natijalarni ko'rish",

    // Theme
    "theme.red": "Qizil",
    "theme.orange": "Sabzirang",
    "theme.yellow": "Sariq",
    "theme.green": "Yashil",
    "theme.blue": "Ko'k",
    "theme.purple": "Binafsha",
    "theme.default": "Standart",

    // Test Preview
    "test_preview.title": "Test Ko'rinishi",
    "test_preview.question": "Savol",
    "test_preview.correct_answer": "To'g'ri javob",
    "test_preview.start_test": "Testni boshlash",
    "test_preview.true": "To'g'ri",
    "test_preview.false": "Noto'g'ri",
    "test_preview.matches": "Mosliklar",
    "test_preview.options": "Variantlar",
    "test_preview.no_questions": "Savollar mavjud emas",

    // Monitor
    "monitor.title": "Test monitoringi",
    "monitor.subtitle": "Test jarayoni va ishtirokchilar faoliyatini kuzatish",
    "monitor.starting": "Boshlanmoqda...",
    "monitor.start": "Testni boshlash",
    "monitor.resume": "Testni davom ettirish",
    "monitor.pause": "Testni to'xtatish",
    "monitor.preview": "Ko'rib chiqish",
    "monitor.attention": "Diqqat",
    "monitor.time_remaining": "Qolgan vaqt",
    "monitor.participants": "Ishtirokchilar",
    "monitor.average_progress": "O'rtacha progress",
    "monitor.participants_tab": "Ishtirokchilar",
    "monitor.results_tab": "Natijalar",
    "monitor.participants_list": "Ishtirokchilar ro'yxati",
    "monitor.participant_actions": "Harakatlar",
    "monitor.view_details": "Tafsilotlarni ko'rish",
    "monitor.send_message": "Xabar yuborish",
    "monitor.remove_participant": "Ishtirokchini olib tashlash",
    "monitor.avg_score": "O'rtacha ball",
    "monitor.completion_rate": "Tugatish darajasi",
    "monitor.avg_time": "O'rtacha vaqt",
    "monitor.detailed_results": "Batafsil natijalar",
    "monitor.detailed_results_desc": "Individual ko'rsatkichlarning batafsil tahlili",
    "monitor.generate_report": "Hisobot yaratish",
    "monitor.export_results": "Natijalarni eksport qilish",
    "monitor.access_code": "Kirish kodi",
    "monitor.qr_code": "QR kod",
    "monitor.waiting_participants": "Ishtirokchilar kutilmoqda",
    "monitor.participants_appear": "Ishtirokchilar testga qo'shilganda shu yerda paydo bo'ladi",
    "monitor.no_results": "Natijalar mavjud emas",
    "monitor.results_available": "Natijalar ishtirokchilar testni tugatgandan so'ng mavjud bo'ladi",

    // Saved Tests
    "saved.title": "Saqlangan testlar",
    "saved.subtitle": "Saqlangan testlarni ko'rish va boshqarish",

    // Create Test
    "create.title": "Test yaratish",
    "create.subtitle": "Sun'iy intellekt yordamida yangi test yaratish",
    "create.connected": "Serverga ulangan",
    "create.not_connected": "Serverga ulanmagan",
    "create.choose_method": "Usulni tanlang",
    "create.configure_test": "Testni sozlash",
    "create.preview_test": "Testni ko'rib chiqish",
    "create.form_method": "Forma orqali yaratish",
    "create.form_desc": "Test yaratish uchun fan, mavzular va boshqa ma'lumotlarni kiriting",
    "create.book_method": "Kitob orqali yaratish",
    "create.book_desc": "Kitobni yuklang (PDF, DOCX, TXT) va test yaratish uchun mavzularni tanlang",
    "create.drag_drop": "Faylingizni shu yerga tashlang",
    "create.file_types": "PDF, DOCX va TXT formatlarini qo'llab-quvvatlaydi",
    "create.browse_files": "Fayllarni ko'rish",
    "create.remove": "Olib tashlash",
    "create.process_book": "Kitobni qayta ishlash",
    "create.processing": "Kitob qayta ishlanmoqda...",
    "create.extracted_topics": "Ajratib olingan mavzular",
    "create.select_topics": "Testingizga kiritmoqchi bo'lgan mavzularni tanlang",
    "create.subject": "Fan",
    "create.subject_placeholder": "masalan, Matematika, Fizika, Tarix",
    "create.topic": "Mavzu",
    "create.topic_placeholder": "masalan, Algebra, Hisoblash, Geometriya",
    "create.difficulty": "Qiyinlik",
    "create.easy": "Oson",
    "create.medium": "O'rta",
    "create.hard": "Qiyin",
    "create.format": "Format",
    "create.multiple_choice": "Ko'p tanlovli",
    "create.true_false": "To'g'ri/Noto'g'ri",
    "create.short_answer": "Qisqa javob",
    "create.language": "Til",
    "create.number_of_questions": "Savollar soni",
    "create.additional_instructions": "Qo'shimcha ko'rsatmalar (ixtiyoriy)",
    "create.instructions_placeholder": "Test uchun har qanday maxsus ko'rsatmalar yoki talablar",
    "create.generating": "Yaratilmoqda...",
    "create.generate_ai": "Sun'iy intellekt bilan yaratish",
    "create.generating_test": "Test yaratilmoqda...",
    "create.skip_loading": "Yuklanishni o'tkazib yuborish",
    "create.save_test": "Testni saqlash",
    "create.test_saved": "Test muvaffaqiyatli saqlandi!",

    // Analytics
    "analytics.title": "Tahlillar paneli",
    "analytics.subtitle": "Test samaradorligi va foydalanuvchilar faolligi bo'yicha keng qamrovli ma'lumotlar.",
    "analytics.overview": "Umumiy ko'rinish",
    "analytics.performance": "Samaradorlik",
    "analytics.subjects": "Fanlar",
    "analytics.timeframe": "Vaqt oralig'i",
    "analytics.filter": "Filtr",
    "analytics.download": "Hisobotni yuklab olish",
    "analytics.tests_created": "Yaratilgan testlar",
    "analytics.participants": "Ishtirokchilar",
    "analytics.completion_rate": "Tugatish darajasi",
    "analytics.avg_score": "O'rtacha ball",
    "analytics.from_last_month": "o'tgan oydan",
    "analytics.test_activity": "Test faoliyati",
    "analytics.test_activity_desc": "Vaqt davomida yaratilgan testlar va ishtirokchilar soni",
    "analytics.performance_dist": "Samaradorlik taqsimoti",
    "analytics.performance_dist_desc": "Barcha ishtirokchilar orasida test natijalarining taqsimlanishi",
    "analytics.subject_dist": "Fanlar bo'yicha taqsimot",
    "analytics.subject_dist_desc": "Testlarning fan sohalari bo'yicha taqsimlanishi",
    "analytics.recent_tests": "So'nggi testlar",
    "analytics.view_all": "Barchasini ko'rish",
    "analytics.test_name": "Test nomi",
    "analytics.subject": "Fan",
    "analytics.participants_count": "Ishtirokchilar",
    "analytics.avg_score_label": "O'rt. ball",
    "analytics.date": "Sana",
    "analytics.chart_type": "Diagramma turi",
    "analytics.bar": "Ustun",
    "analytics.line": "Chiziq",
    "analytics.area": "Maydon",
    "analytics.showing_data": "Ma'lumotlar ko'rsatilmoqda",
    "analytics.months": "oylar uchun",
    "analytics.performance_chart": "Samaradorlik taqsimoti diagrammasi",
    "analytics.subject_chart": "Fanlar bo'yicha taqsimot diagrammasi",

    // Pricing
    "pricing.title": "Narxlash rejalari",
    "pricing.subtitle": "Ehtiyojlaringizga eng mos keladigan rejani tanlang",
    "pricing.popular": "Mashhur",
    "pricing.per_month": "/oy",
    "pricing.select_plan": "Rejani tanlash",
    "pricing.basic": "Asosiy",
    "pricing.basic_desc": "Kichik testlar uchun asosiy funksiyalar",
    "pricing.standard": "Standart",
    "pricing.standard_desc": "Professional foydalanish uchun kengaytirilgan funksiyalar",
    "pricing.premium": "Premium",
    "pricing.premium_desc": "Korxona darajasidagi test yechimi",
    "pricing.plan_selected": "Reja tanlandi",
    "pricing.test_ready": "Testingiz ulashishga tayyor",
    "pricing.unique_code": "Noyob kirish kodi",
    "pricing.share_code": "Testga qo'shilish uchun bu kodni ishtirokchilar bilan ulashing",
    "pricing.scan_qr": "Testga qo'shilish uchun ushbu QR kodni skanerlang",
    "pricing.invite_link": "Taklif havolasi",
    "pricing.share_link": "Testga qo'shilish uchun bu havolani ishtirokchilar bilan ulashing",
    "pricing.back_to_plans": "Rejalarga qaytish",
    "pricing.go_to_monitoring": "Monitoringga o'tish",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: () => "",
  translations,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "ru", "uz"].includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    if (typeof window !== "undefined") {
      localStorage.setItem("language", newLanguage)
    }
  }

  const t = (key: string): string => {
    const currentTranslations = translations[language] || translations.en
    return currentTranslations[key] || key
  }

  // Prevent hydration mismatch
  if (!mounted) {
    return <div style={{ visibility: "hidden" }}>{children}</div>
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>{children}</LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
