export const ONLINE_TEST_EVENTS = {
  START_TEST: "start:test",
  TEST_STARTED: "test:started",
  START_ONLINE_TEST: "start:online:test",
  ONLINE_TEST_STARTED: "online:test:started",
  FINISH_ONLINE_TEST: "finish:online:test",
  ONLINE_TEST_ENDED: "online:test:ended",
  JOIN_ONLINE_TEST: "join:online:test",
  LEAVE_ONLINE_TEST: "leave:online:test",
  CHANGE_USER_DATA: "change:user:data",
  USER_JOINED: "user:joined",
  USER_LEFT: "user:left",
  PROGRESS_UPDATED: "progress:updated",
  ERROR: "error",
}
